### ISSUE TITLE
add to userneed 5 a  wysiwyg should be available for editing 

### ISSUE THREAD

**Issue by lseeman** [w3c/ctaur#76]
A wysiwyg should be available for editing . Add that editing to not require multiple screens or multi step. For example I can add content and see its effect. without toggling tabs or screen.

**Comment by sehollier** [comment]
The collaboration tools document needs to support a variety of different tools, including command line tools which would not have a wysiwyg editor. Therefore it is not possible to provide a wysiwyg editor in all scenarios. Instead, the Note supports editing functionality based on purpose of the tool. This may include a wysiwyg editor but it may include other options such as command line interface. Therefore this issue is rejected.
